In [1]:
import pandas as pd
import numpy as np
train = pd.read_csv('../input/tweet-sentiment-extraction/train.csv')

pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 500)

In [2]:
train.head()

,textID,text,selected_text,sentiment
0,cb774db0d1,"I`d have responded, if I were going","I`d have responded, if I were going",neutral
1,549e992a42,Sooo SAD I will miss you here in San Diego!!!,Sooo SAD,negative
2,088c60f138,my boss is bullying me...,bullying me,negative
3,9642c003ef,what interview! leave me alone,leave me alone,negative
4,358bd9e861,"Sons of ****, why couldn`t they put them on t...","Sons of ****,",negative

In [13]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27481 entries, 0 to 27480
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   textID         27481 non-null  object
 1   text           27480 non-null  object
 2   selected_text  27480 non-null  object
 3   sentiment      27481 non-null  object
dtypes: object(4)
memory usage: 858.9+ KB

In [4]:
train_neutral = train.query("sentiment=='neutral'")

In [5]:
train_neutral.head()

,textID,text,selected_text,sentiment
0,cb774db0d1,"I`d have responded, if I were going","I`d have responded, if I were going",neutral
5,28b57f3990,http://www.dothebouncy.com/smf - some shameles...,http://www.dothebouncy.com/smf - some shameles...,neutral
7,50e14c0bb8,Soooo high,Soooo high,neutral
8,e050245fbd,Both of you,Both of you,neutral
10,2339a9b08b,"as much as i love to be hopeful, i reckon the...","as much as i love to be hopeful, i reckon the ...",neutral

In [8]:
train_neutral.shape

(11118, 4)

In [23]:
train_neutral.dropna(axis=0)

,textID,text,selected_text,sentiment,len_text
0,cb774db0d1,"I`d have responded, if I were going","I`d have responded, if I were going",neutral,36.0
5,28b57f3990,http://www.dothebouncy.com/smf - some shameles...,http://www.dothebouncy.com/smf - some shameles...,neutral,92.0
7,50e14c0bb8,Soooo high,Soooo high,neutral,10.0
8,e050245fbd,Both of you,Both of you,neutral,12.0
10,2339a9b08b,"as much as i love to be hopeful, i reckon the...","as much as i love to be hopeful, i reckon the ...",neutral,107.0
...,...,...,...,...,...
27468,a753a93e45,"few grilled mushrooms and olives, feta cheese ...","few grilled mushrooms and olives, feta cheese ...",neutral,101.0
27469,ac92790d8b,94 more days till BH comes back to LA,94 more days till BH comes back to LA,neutral,37.0
27471,15bb120f57,"i`m defying gravity. and nobody in alll of oz,...","i`m defying gravity. and nobody in alll of oz,...",neutral,106.0
27473,a208770a32,in spoke to you yesterday and u didnt respond...,in spoke to you yesterday and u didnt respond ...,neutral,67.0
27480,6f7127d9d7,All this flirting going on - The ATG smiles...,All this flirting going on - The ATG smiles. Y...,neutral,62.0

In [44]:
train_neutral['len_text'] = train_neutral['text'].str.len()
train_neutral['len_selected_text'] = train_neutral['selected_text'].str.len()
train_neutral.head(100)
#same_len_df = train_neutral[train_neutral.text.apply(len)==train_neutral.selected_text.apply(len)]
#same_len_df.shape

/Users/fyk7/venv_python/test_env/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/Users/fyk7/venv_python/test_env/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,textID,text,selected_text,sentiment,len_text,len_selected_text
0,cb774db0d1,"I`d have responded, if I were going","I`d have responded, if I were going",neutral,36.0,35.0
5,28b57f3990,http://www.dothebouncy.com/smf - some shameles...,http://www.dothebouncy.com/smf - some shameles...,neutral,92.0,92.0
7,50e14c0bb8,Soooo high,Soooo high,neutral,10.0,10.0
8,e050245fbd,Both of you,Both of you,neutral,12.0,11.0
10,2339a9b08b,"as much as i love to be hopeful, i reckon the...","as much as i love to be hopeful, i reckon the ...",neutral,107.0,106.0
...,...,...,...,...,...,...
230,ae21c1ac38,The exception for a short dude: Larenz fineass...,The exception for a short dude: Larenz fineass...,neutral,55.0,55.0
233,148ac38bea,Yes i work 6 to 3...,Yes i work 6 to 3...,neutral,21.0,20.0
234,641555ac70,"Hmmm, maybe that`s what they meant. They elud...","Hmmm, maybe that`s what they meant. They elude...",neutral,101.0,100.0
235,4bda359cbb,Done at the spa now meeting vic for some lat...,Done at the spa now meeting vic for some lat...,neutral,54.0,54.0
237,1af124bc1c,Always have wanted to go to Oz,Always have wanted to go to Oz,neutral,31.0,30.0

In [31]:
len_tra_neu = len(train_neutral)
same_length = train_neutral[train_neutral.len_text==train_neutral.len_selected_text]
len(same_length)/len_tra_neu*100

53.33693110271631

In [42]:
diff_one_word_len = train_neutral[train_neutral.len_text - 1==train_neutral.len_selected_text]
len(diff_one_word_len)/len_tra_neu*100

34.52959165317503

In [43]:
diff_one_word_len = train_neutral[train_neutral.len_text - 2==train_neutral.len_selected_text]
len(diff_one_word_len)/len_tra_neu*100

3.5887749595250944

In [46]:
not_same_len = train_neutral[train_neutral.len_text - train_neutral.len_selected_text > 10]
not_same_len.head()

,textID,text,selected_text,sentiment,len_text,len_selected_text
35,4f5267ad70,"Thats it, its the end. Tears for Fears vs Eric...","Thats it, its the end. Tears for Fears",neutral,84.0,38.0
57,6086b1f016,will be back later. http://plurk.com/p/rp3k7,will be back later.,neutral,45.0,19.0
110,9c4817f73b,if u have a friendster add me!!!!!!!!! ...,if u have a friendster add me!!!!!!!!! ...,neutral,126.0,107.0
198,931a866d3f,Had nicotine replacement patch on for 4 hours....,"So far, so good, but I did sleep for most of t...",neutral,132.0,85.0
199,7a718b23ef,_Sanderson What`s with Twatter lately? Either...,What`s with Twatter lately? Either I can`t ge...,neutral,91.0,80.0

In [48]:
len(not_same_len)/len_tra_neu*100

5.054865983090484